# Generated by Django 3.2.15 on 2023-05-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_date_added', models.DateField(auto_now_add=True)),
                ('headline', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=500)),
                ('identify_holder', models.CharField(blank=True, max_length=500, null=True)),
                ('estate_reg', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('value_delineation', models.CharField(max_length=60)),
                ('delineation_date', models.DateField(blank=True, null=True)),
                ('delineation_payment', models.CharField(max_length=40)),
                ('consecutive_delineation', models.CharField(max_length=40)),
                ('visited_by', models.CharField(max_length=70)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, max_length=1000, null=True)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('review', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('underReview', models.BooleanField(default=False)),
                ('underReview_date', models.DateField(blank=True, null=True)),
                ('is_notified', models.CharField(blank=True, max_length=20, null=True)),
                ('is_notified_date', models.DateField(blank=True, null=True)),
                ('is_notified_observation', models.TextField(blank=True, max_length=1000, null=True)),
                ('correct_document', models.CharField(blank=True, max_length=20, null=True)),
                ('correct_document_date', models.DateField(blank=True, null=True)),
                ('process_act_num', models.CharField(blank=True, max_length=500, null=True)),
                ('process_act_num_date', models.DateField(blank=True, null=True)),
                ('liquidation_value', models.CharField(blank=True, max_length=500, null=True)),
                ('is_personal_notified', models.CharField(blank=True, max_length=20, null=True)),
                ('is_personal_notified_date', models.DateField(blank=True, null=True)),
                ('is_personal_notified_observation', models.TextField(blank=True, max_length=1000, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('payment_status_date', models.DateField(blank=True, null=True)),
                ('payment_receipt_number', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_receipt_date', models.DateField(blank=True, null=True)),
                ('license_value', models.CharField(blank=True, max_length=500, null=True)),
                ('delineation_tax_value', models.CharField(blank=True, max_length=500, null=True)),
                ('resolution_number', models.CharField(blank=True, max_length=500, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('resolution_notification_date', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VeriyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Copia_de_cedula_del_propietario_pasaporte', models.BooleanField(default=False)),
                ('Certificado_de_tradición_y_libertad', models.BooleanField(default=False)),
                ('Copia_de_la_escritura', models.BooleanField(default=False)),
                ('Paz_y_salvo_municipal', models.BooleanField(default=False)),
                ('Copia_del_impuesto_predial', models.BooleanField(default=False)),
                ('Certificado_catastral', models.BooleanField(default=False)),
                ('Planos_arquitectónicos_y_estructurales', models.BooleanField(default=False)),
                ('Planos_topográficos', models.BooleanField(default=False)),
                ('CD_o_USB', models.BooleanField(default=False)),
                ('Copia_de_la_tarjeta_profesional', models.BooleanField(default=False)),
                ('Formulario_único_nacional', models.BooleanField(default=False)),
                ('Certificado_de_delineación_y_comprobante_de_pago', models.BooleanField(default=False)),
                ('Viabilidad_de_energía_y_acueducto', models.BooleanField(default=False)),
                ('Viabilidad_de_alcantarillado_y_aseo', models.BooleanField(default=False)),
                ('Certificado_de_sismo_resistencia', models.BooleanField(default=False)),
                ('Memorias_de_calculo', models.BooleanField(default=False)),
                ('Estudio_de_suelos', models.BooleanField(default=False)),
                ('Peritaje_técnico', models.BooleanField(default=False)),
                ('Plan_de_majo_ambiental', models.BooleanField(default=False)),
                ('Plan_de_manejo_de_escombros', models.BooleanField(default=False)),
                ('Plan_de_manejo_de_transito', models.BooleanField(default=False)),
                ('Avaluó_comercial', models.BooleanField(default=False)),
                ('Declaración_de_antigüedad', models.BooleanField(default=False)),
                ('Declaración_de_no_bienes', models.BooleanField(default=False)),
                ('Declaración_extrajuicio_de_sana_posesión', models.BooleanField(default=False)),
                ('Copia_de_licencia', models.BooleanField(default=False)),
                ('Certificado_de_nomenclatura', models.BooleanField(default=False)),
                ('Certificado_del_sisben', models.BooleanField(default=False)),
                ('Certificado_de_desplazado', models.BooleanField(default=False)),
                ('Carta_de_aceptación_por_revisor', models.BooleanField(default=False)),
                ('Poder_autenticado', models.BooleanField(default=False)),
                ('Autorización_autenticada', models.BooleanField(default=False)),
                ('Solicitud', models.BooleanField(default=False)),
                ('Certificado_financiero', models.BooleanField(default=False)),
                ('Contrato_de_promesa_de_compraventa', models.BooleanField(default=False)),
                ('filev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifyDoc', to='filed.file')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='State_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filed.statetype'),
        ),
        migrations.AddField(
            model_name='file',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filed.agent'),
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='filed.category'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filed.filetype'),
        ),
        migrations.AddField(
            model_name='file',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
