# Generated by Django 3.2.15 on 2023-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
